 # --- Basic options --- #

# Name of website
title: Seminar Anti-Social Distancing: Master’s Meet & Greet

# Short description of your site
description: A seminar to counteract the social distance that Corona brought to us.

# Your name to show in the footer
author: Lena Gieseke
